import type { Preset } from '../types';

export const builtInPresets: Preset[] = [
  {
    id: 'cityscape',
    name: 'Cityscape',
    params: {
      seed: 42891,
      grid: { rows: 30, cols: 30, spacing: 0.15, angle: 45 },
      blocks: {
        minHeight: 0.2,
        maxHeight: 4.0,
        width: 0.8,
        depth: 0.8,
        heightAlgorithm: 'perlin',
      },
      colors: {
        background: '#0a0a0a',
        primary: '#ffffff',
        secondary: '#333333',
        gradient: true,
        shadingStyle: 'standard',
      },
      scene: {
        density: 0.5,
        gridLines: 0.5,
        dots: 0.2,
        elevatedBars: 0.3,
      },
    },
    createdAt: 0,
    isBuiltIn: true,
  },
  {
    id: 'circuit',
    name: 'Circuit Board',
    params: {
      seed: 12345,
      grid: { rows: 40, cols: 40, spacing: 0.2, angle: 45 },
      blocks: {
        minHeight: 0.1,
        maxHeight: 1.5,
        width: 0.6,
        depth: 0.6,
        heightAlgorithm: 'random',
      },
      colors: {
        background: '#0a0a0a',
        primary: '#00ff88',
        secondary: '#003322',
        gradient: true,
        shadingStyle: 'standard',
      },
      scene: {
        density: 0.35,
        gridLines: 0.7,
        dots: 0.3,
        elevatedBars: 0.1,
      },
    },
    createdAt: 0,
    isBuiltIn: true,
  },
  {
    id: 'waves',
    name: 'Sound Waves',
    params: {
      seed: 77777,
      grid: { rows: 25, cols: 50, spacing: 0.05, angle: 45 },
      blocks: {
        minHeight: 0.1,
        maxHeight: 3.0,
        width: 0.9,
        depth: 0.9,
        heightAlgorithm: 'sine',
      },
      colors: {
        background: '#0a0a0a',
        primary: '#ff6600',
        secondary: '#331100',
        gradient: true,
        shadingStyle: 'standard',
      },
      scene: {
        density: 0.6,
        gridLines: 0.2,
        dots: 0.1,
        elevatedBars: 0.15,
      },
    },
    createdAt: 0,
    isBuiltIn: true,
  },
  {
    id: 'ripple',
    name: 'Ripple',
    params: {
      seed: 55555,
      grid: { rows: 35, cols: 35, spacing: 0.1, angle: 45 },
      blocks: {
        minHeight: 0.1,
        maxHeight: 2.5,
        width: 0.7,
        depth: 0.7,
        heightAlgorithm: 'wave',
      },
      colors: {
        background: '#0a0a0a',
        primary: '#6699ff',
        secondary: '#112244',
        gradient: true,
        shadingStyle: 'standard',
      },
      scene: {
        density: 0.45,
        gridLines: 0.4,
        dots: 0.15,
        elevatedBars: 0.2,
      },
    },
    createdAt: 0,
    isBuiltIn: true,
  },
  {
    id: 'sparse',
    name: 'Sparse Grid',
    params: {
      seed: 99999,
      grid: { rows: 20, cols: 20, spacing: 0.4, angle: 45 },
      blocks: {
        minHeight: 0.5,
        maxHeight: 5.0,
        width: 0.5,
        depth: 0.5,
        heightAlgorithm: 'random',
      },
      colors: {
        background: '#0a0a0a',
        primary: '#ffffff',
        secondary: '#444444',
        gradient: true,
        shadingStyle: 'standard',
      },
      scene: {
        density: 0.25,
        gridLines: 0.6,
        dots: 0.25,
        elevatedBars: 0.35,
      },
    },
    createdAt: 0,
    isBuiltIn: true,
  },
  {
    id: 'dense',
    name: 'Dense City',
    params: {
      seed: 33333,
      grid: { rows: 45, cols: 45, spacing: 0.02, angle: 45 },
      blocks: {
        minHeight: 0.1,
        maxHeight: 2.0,
        width: 0.95,
        depth: 0.95,
        heightAlgorithm: 'perlin',
      },
      colors: {
        background: '#0a0a0a',
        primary: '#ffcc00',
        secondary: '#332200',
        gradient: true,
        shadingStyle: 'standard',
      },
      scene: {
        density: 0.7,
        gridLines: 0.3,
        dots: 0.05,
        elevatedBars: 0.1,
      },
    },
    createdAt: 0,
    isBuiltIn: true,
  },
];
